add pcap_to_pandas functionality to netml
chicago-cdac/netml pull request #18
Opened 2022-10-29 00:26 UTC by feamster

tested this against notebooks that previously used pcap_to_pandas.  have test script, can check it in somewhere if I know where...

2022-10-31 19:18 UTC, feamster commented
@jesteria I've asked @staveesh to review this pull request for us, since he's taking the class as well.

2022-10-31 20:57 UTC, staveesh requested changes
@feamster @jesteria I tested the `pcap_to_pandas` function on a netflix PCAP and it produced a valid DataFrame. Only a couple of minor changes may be needed further:

1. We may want to convert the byte strings `dns_query` and `dns_resp` to strings.
2. We may want to add the package `netaddr` to `setup.py` as I had to install it explicitly to make it work.

2022-10-31 20:57 UTC, staveesh commented on src/netml/pparser/parser.py
> +import netaddr
Replacement required in `setup.py` file:
```
INSTALL_REQUIRES = [
    'numpy ~= 1.23.3',
    'pandas ~= 1.5.0',
    'pyod ~= 1.0.5',
    'scapy ~= 2.4.5',
    'scikit-learn ~= 1.1.2',
    'netaddr ~= 0.8.0',
]
```

2022-10-31 20:57 UTC, staveesh commented on src/netml/pparser/parser.py
> +                    if DNSQR in pkt:
Might want to convert byte strings to strings here.

```
                    if DNSQR in pkt:
                        pkt_dict["is_dns"] = True
                        pkt_dict["dns_query"] = str(pkt[DNSQR].qname, 'utf-8')
                    if DNSRR in pkt:
                        pkt_dict["is_dns"] = True
                        pkt_dict["dns_resp"] = str(pkt[DNSRR].rrname, 'utf-8')
```

2022-11-01 17:19 UTC, jesteria approved these changes
Thanks folks! :+1:

2022-11-01 17:26 UTC, merged